artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/uc?export=download&id=1HhJVxz5ka1icthgnvD5etjCjGrCY6-0-
  local_data_file: artifacts/data_ingestion/fer2013.zip
  unzip_dir: artifacts/data_ingestion